### ISSUE TITLE
Cannot retrive models.zip

### ISSUE THREAD

**Issue by brmather** [stephaniedurand/SeisTomoPy_V3#2]
Hi Stephanie,

This project looks very interesting. I would like to run some test examples, but on installing the package I am unable to download the `models.zip` file (line 175 in `setup.py`).

```python
urllib.urlretrieve("http://earth.uni-muenster.de/~durand/models.zip","models.zip")
```

Are you able to make sure these data files are available, or point me to where they are now located? A good place to host them is [Zenodo](https://zenodo.org/) because they issue a DOI with your packages.

Let me know if you need a hand with this. Happy to help!

Kind regards,
Ben

**Comment by brmather** [comment]
In case anybody else encounters the same issue, `models.zip` is now located here:

[http://perso.ens-lyon.fr/stephanie.durand/models.zip](http://perso.ens-lyon.fr/stephanie.durand/models.zip)

**Comment by stephaniedurand** [comment]
I have updated my webpage and the url in the setup.py file so now everybody should be fine when installing SeisTomoPy.
Best,
